create table if not exists session (
    id varchar(64) primary key,
    agent_id varchar(128) not null,
    user_id varchar(128) not null,
    channel varchar(64) not null,
    status varchar(64) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists session_message (
    id bigint generated by default as identity primary key,
    session_id varchar(64) not null,
    run_id varchar(64) not null,
    role varchar(32) not null,
    message_type varchar(32) not null,
    content text not null,
    tool_name varchar(128),
    tool_args_json text,
    tool_result_json text,
    seq_no bigint not null,
    created_at timestamp with time zone not null
);

create index if not exists idx_session_message_session_id on session_message(session_id);
create index if not exists idx_session_message_run_id on session_message(run_id);
create unique index if not exists uk_session_message_session_seq on session_message(session_id, seq_no);
