-- V32: Agent 实验室 (Phase 1) —— 系统管理员描述 AI 能力目标 + 测试用例,
-- 后端用 meta-LLM 自动迭代设计 Agent / Skill,跑测试,失败再改,直到通过或上限。
--
-- 隔离原则:meta-LLM 生成的 Agent 和 Skill 全部落在 scope_type='AGENT_LAB' 的
-- 行,跟生产 SYSTEM/TENANT/USER 完全隔离;Phase 2 才加"复制到生产"按钮。
--
-- 评估器(Phase 1 简化版)只支持两类规则:
--   * contains:    assistant 最终文本含某子串
--   * tool_called: 某工具被调用 >= N 次

CREATE TABLE IF NOT EXISTS agent_lab_task (
    id VARCHAR(64) PRIMARY KEY,
    owner_user_id VARCHAR(128) NOT NULL,           -- 创建者(用于权限判定 + 列表归属)
    title VARCHAR(255) NOT NULL,
    goal_description TEXT NOT NULL,                -- 自然语言目标描述
    llm_config_id VARCHAR(64),                     -- meta-LLM 配置 id;NULL = 用 is_default=true 那个
    test_cases_json TEXT NOT NULL,                 -- JSON array of {id, input, rules:[{type, ...}]}
    max_iterations INTEGER NOT NULL DEFAULT 5,
    current_iteration INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING', -- PENDING/RUNNING/SUCCEEDED/FAILED_MAX_ITER/FAILED_META_LLM/CANCELLED
    sandbox_agent_id VARCHAR(128),                 -- 同一任务复用同一个 sandbox agent_id(每轮覆盖 config)
    sandbox_skill_names_json TEXT,                 -- 该任务管的 skill_name 列表 JSON array
    final_summary TEXT,                            -- 终结时人话总结(成功/失败原因)
    error_detail TEXT,                             -- 失败时的技术细节
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_agent_lab_task_owner ON agent_lab_task(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_agent_lab_task_status ON agent_lab_task(status);

CREATE TABLE IF NOT EXISTS agent_lab_iteration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL REFERENCES agent_lab_task(id) ON DELETE CASCADE,
    iteration_no INTEGER NOT NULL,                 -- 1-based
    status VARCHAR(32) NOT NULL DEFAULT 'IN_PROGRESS', -- IN_PROGRESS/EVAL_PASSED/EVAL_FAILED/META_LLM_ERROR
    agent_snapshot_json TEXT,                      -- meta-LLM 本轮产出的 Agent 配置
    skill_snapshots_json TEXT,                     -- meta-LLM 本轮产出的 Skill 列表
    test_results_json TEXT,                        -- 每个测试用例的执行结果 + 评估结果 JSON
    passed_count INTEGER,                          -- 通过用例数(冗余,方便列表显示)
    total_count INTEGER,                           -- 总用例数(冗余)
    evaluation_summary TEXT,                       -- 人话评估摘要(显示给用户)
    fix_plan_json TEXT,                            -- meta-LLM 对下一轮的修复建议
    meta_llm_error TEXT,                           -- meta-LLM 本身调用失败时的错
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_agent_lab_iteration_task ON agent_lab_iteration(task_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_agent_lab_iteration_task_no ON agent_lab_iteration(task_id, iteration_no);
