create table if not exists tool_audit_log (
    id bigint generated by default as identity primary key,
    run_id varchar(64) not null,
    session_id varchar(64) not null,
    agent_id varchar(128) not null,
    request_id varchar(64) not null,
    tool_name varchar(128) not null,
    phase varchar(64) not null,
    allowed boolean not null,
    approval_required boolean not null,
    success boolean,
    executed boolean,
    reason text,
    arguments_json text,
    result_summary text,
    error_message text,
    duration_millis bigint,
    created_at timestamp with time zone not null
);

create index if not exists idx_tool_audit_log_run_id on tool_audit_log(run_id);
create index if not exists idx_tool_audit_log_session_id on tool_audit_log(session_id);
create index if not exists idx_tool_audit_log_tool_name on tool_audit_log(tool_name);
