CREATE TABLE memory_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id VARCHAR(128) NOT NULL,
    session_id VARCHAR(64),
    run_id VARCHAR(64),
    source VARCHAR(64) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_memory_note_agent_id ON memory_note (agent_id);
CREATE INDEX idx_memory_note_session_id ON memory_note (session_id);
