CREATE TABLE IF NOT EXISTS llm_provider_config (
    id VARCHAR(64) PRIMARY KEY,
    provider VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    model VARCHAR(255) NOT NULL,
    base_url VARCHAR(255) NOT NULL,
    api_key TEXT NOT NULL,
    chat_path VARCHAR(255) NOT NULL,
    stream_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE run_record ADD COLUMN IF NOT EXISTS llm_config_id VARCHAR(64);
ALTER TABLE run_record ADD COLUMN IF NOT EXISTS llm_provider VARCHAR(64);
ALTER TABLE run_record ADD COLUMN IF NOT EXISTS llm_model VARCHAR(255);
